services:
  - type: web
    name: movie-recs-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOW_ORIGINS
        value: "*"
    autoDeploy: true
    plan: free